### ISSUE TITLE
Unknown date format error

### ISSUE THREAD

**Issue by sergeeximius** [hstern/dwhois#5]
The first launch and immediately an error

```
Python 3.9.6 (default, Jun 28 2021, 19:24:41)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> d = whois.query('eximius.ru')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ssedov/Work/PyCode/whois-test/.env/lib/python3.9/site-packages/whois/__init__.py", line 42, in query
    return Domain(pd) if pd['domain_name'][0] else None
  File "/Users/ssedov/Work/PyCode/whois-test/.env/lib/python3.9/site-packages/whois/_3_adjust.py", line 15, in __init__
    self.creation_date = str_to_date(data['creation_date'][0])
  File "/Users/ssedov/Work/PyCode/whois-test/.env/lib/python3.9/site-packages/whois/_3_adjust.py", line 95, in str_to_date
    raise ValueError("Unknown date format: '{0}'".format(s))
ValueError: Unknown date format: '1994-04'
```

**Comment by hstern** [comment]
Hi Sergey,

this package is abandoned. Feel free to fork.

henry
